{% set name = "websocket-client" %}
{% set snakename = "websocket_client" %}
{% set bundle = "tar.gz" %}
{% set version = "0.58.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ snakename }}/{{ snakename }}-{{ version }}.{{ bundle }}
  sha256: 63509b41d158ae5b7f67eb4ad20fecbb4eee99434e73e140354dc3ff8e09716f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # Cannot be no-arch due to bytecode issues.

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - python
    - six

test:
  imports:
    - websocket
    - websocket.tests

about:
  home: https://github.com/liris/websocket-client
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: WebSocket client for python. hybi13 is supported.
  dev_url: https://github.com/liris/websocket-client

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
